FROM python:3.9-slim
WORKDIR /app
RUN apt-get update && apt-get install -y\
    ffmpeg\
    libsndfile1\
    && rm -rf /var/lib/apt/lists/*


COPY requirements.txt .
Run pip install requirements.txt .
COPY . .
EXPOSE 8000
CMD ["uvicorn","main:app","--host","0.0.0.0","--port","8000"]